language: java
jdk:
  - oraclejdk8

notifications:
  slack:
    rooms:
      - pictopage:GgJNEnLcl4annmdzEwdCVbqY#random

before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
